GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO aravindh;

create or replace procedure transfer_another(
   sender int,
   receiver int,
   amount dec
)
language plpgsql
as $$
begin
    -- subtracting the amount from the sender's account
    update accounts
    set balance = balance - amount
    where id = sender;

    -- adding the amount to the receiver's account
    update accounts
    set balance = balance + amount
    where id = receiver;


end;$$

;
drop table if exists accounts_old;

create table accounts_old (
    id int generated by default as identity,
    name varchar(100) not null,
    balance dec(15,2) not null,
    old_balance dec(13,2) not null,
    primary key(id)
);

insert into accounts_old(name,balance, old_balance)
values('Bob',10000, 10000);

insert into accounts_old(name,balance, old_balance)
values('Alice',10000, 10000 );


create or replace procedure transfer(
   sender int,
   receiver int,
   amount dec
)
language plpgsql
as $$
begin
    -- subtracting the amount from the sender's account
    update accounts
    set balance = balance - amount
    where id = sender;

    -- adding the amount to the receiver's account
    update accounts
    set balance = balance + amount
    where id = receiver;

end;$$;